// <auto-generated />
using System;
using LateralGroup.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LateralGroup.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CmsWriteDbContext))]
    partial class CmsWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LateralGroup.Domain.Entities.CmsContentItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabledByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabledByCms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastEventTimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LatestKnownVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LatestPublishedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDisabledByAdmin");

                    b.HasIndex("IsDisabledByCms");

                    b.HasIndex("IsPublished");

                    b.HasIndex("LastEventTimestampUtc");

                    b.HasIndex("IsPublished", "IsDisabledByCms", "IsDisabledByAdmin");

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("LateralGroup.Domain.Entities.CmsContentVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPublished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasUnpublished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("ObservedAtUtc");

                    b.HasIndex("ContentItemId", "Version")
                        .IsUnique();

                    b.ToTable("ContentVersions", (string)null);
                });

            modelBuilder.Entity("LateralGroup.Domain.Entities.ProcessedCmsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawEventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("Status");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ContentItemId", "TimestampUtc");

                    b.ToTable("ProcessedCmsEvents", (string)null);
                });

            modelBuilder.Entity("LateralGroup.Domain.Entities.CmsContentVersion", b =>
                {
                    b.HasOne("LateralGroup.Domain.Entities.CmsContentItem", "ContentItem")
                        .WithMany("Versions")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("LateralGroup.Domain.Entities.CmsContentItem", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
